### ISSUE TITLE
joblib-spark doesn't work with joblib 1.4.0

### ISSUE THREAD

**Issue by thinkall** [joblib/joblib-spark#51]
joblib 1.4.0 just released two days ago, it will break joblib-spark:
```
        if SafeFunction is None:
            # pylint: disable=protected-access,used-before-assignment
            return self._get_pool().apply_async(
>               PoolManagerMixin._wrap_func_call, (run_on_worker_and_fetch_result,),
                callback=callback, error_callback=callback
            )
E           AttributeError: type object 'PoolManagerMixin' has no attribute '_wrap_func_call'

/usr/lib/miniforge3/envs/pytest/lib/python3.10/site-packages/joblibspark/backend.py:214: AttributeError
```

**Comment by wbo4958** [comment]
I think this issue has been fixed by https://github.com/joblib/joblib-spark/pull/55.

**Comment by thinkall** [comment]
> I think this issue has been fixed by #55.

Right. We need a new release of joblib-spark. @WeichenXu123 , could you please help on this? Thanks.

**Comment by WeichenXu123** [comment]
Published: https://pypi.org/project/joblibspark/0.5.3/
